- curtsies/input.py
> fixed various formatting issues

- curtsies/escseqparse.py
This is a first part to fix #76.
> Fix arguments given to split

- tests/test_window.py
> Check isatty instead

- curtsies/escseqparse.py
- tests/test_fmtstr.py
> Fix: multiple styling tokens in ANSI escape sequence

- curtsies/formatstring.py
- tests/test_fmtstr.py
> Handling of unsupported SGR codes

- curtsies/formatstring.py
- docs/FmtStr.rst
See #101 
https://docs.python.org/3.6/library/stdtypes.html#str.splitlines
> Implement splitlines method of FmtStr class

- tests/test_terminal.py
Skip terminal tests locally that weren't passing no Travis
> expect terminal tests skipped on Travis to fail

- curtsies/curtsieskeys.py
Should fix missing Ctrl-DELETE sequence for #104.
> Include escape sequence for Ctrl-DELETE in curtsieskeys

- .travis.yml
- curtsies/formatstring.py
- setup.py
- tests/test_fmtstr.py
> Width aware perf

- docs/FmtStr.rst
Maybe it should go in a different section but as #30 says it's a common use case so I put it near the top.
> Add available colours and styles to docs

- curtsies/input.py
> Add Input option to disable terminal start/stop

- docs/Input.rst
- docs/terminal_output.py
Documentation now builds in Python 2 and Python 3.
> Migrate doc generation to Python3

- readme.md
@thomasballinger suggested removing this
> removed python2 help

- curtsies/window.py
Removed the backslash before the open square
bracket to fix issue with invalid escape sequence.
Fixes #128
> Fixed escape sequence issue

- curtsies/events.py
> Remove unused imports

- setup.md
Added how to easily auto format from inside VS code to setup.md file.
> Vs code auto format

- curtsies/__init__.py
- curtsies/termhelpers.py
- setup.py
View at https://test.pypi.org/project/curtsies/0.3.2/
> Pypi format fix

- examples/tron.py
I think the command line tron game i made could make a good addition to the examples.
here's a 'gif' (mp4) of it https://i.imgur.com/y0AsysA.mp4
> add tron game to examples

- curtsies/input.py
Looks like this has been broken since 3.5, causing https://github.com/bpython/bpython/issues/910
> Fix sigint on Python 3.5+

- curtsies/fmtfuncs.py
- curtsies/formatstring.py
- curtsies/termformatconstants.py
This PR adds simple italic support the same way all other text styles are supported. I tested only a few things, but it should work as I basically copy-pasted and adjusted the ways already used.
> Add italic support
